examen2/api/urls.py
from django.urls import path
from api import views

app_name = "api"
urlpatterns = [
    
]

examen2/core/urls.py
from django.urls import path

from core import views

from .models import *

app_name = "core"
urlpatterns = [
    ##Estadio
    path('list1/stadium/',views.List1.as_view(), name="list1"),
    path('create/Stadium/',views.CreateStadium.as_view(), name="create1"),
    path('detail/Stadium/<int:pk>/', views.DetailStadium.as_view(), name= "detailone"),
    path('update/Stadium/<int:pk>/', views.UpdateStadium.as_view(), name= "Update1"),
    path('delete/Stadium/<int:pk>/', views.DeleteStadium.as_view(), name= "delete1"),
    ##Equipo
    path('list2/team/',views.List2.as_view(), name="list2"),
    path('create2/team/',views.CreateTeam.as_view(), name="create2"),
    path('detail/team/<int:pk>/', views.DetailTeam.as_view(), name= "detailtwo"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name= "Update2"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name= "delete2"),
    ##Ciudad
    path('list3/city/',views.List3.as_view(), name="list3"),
    path('create3/city/',views.CreateCity.as_view(), name="create3"),
    path('detail/city/<int:pk>/', views.DetailCity.as_view(), name= "detailthree"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name= "Update3"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name= "delete3"),
    

    # Relacion
    path('relationships/', views.relationship_list, name='relationship_list'),

]

examen2/principal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/core/models.py
# from django.contrib.auth.models import User
# from django.db import models

# # Create your models here.

# class City(models.Model):
#     id = models.IntegerField(primary_key=True)
#     ciudad = models.CharField(max_length=128, null=True)

# class Stadium(models.Model):
#     num = models.IntegerField(primary_key=True, default=0)
#     nombre = models.CharField(max_length=128, default='20')  # Establece una cadena vacía como valor predeterminado
#     description = models.CharField(max_length=256, default='30')

#     def __str__(self):
#         return self.nombre



# class Team(models.Model):
#     codigo = models.IntegerField(primary_key=True, default=0)
#     equipo = models.CharField(max_length=128, null=True)
#     liga = models.CharField(max_length=256, null=True)

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
# from django.db import models


# class City(models.Model):
#     ciudad = models.CharField(max_length=128, blank=True, null=True)

#     class Meta:
#         managed = False
#         db_table = 'City'


# class Stadium(models.Model):
#     num = models.AutoField(primary_key=True)
#     estadio = models.IntegerField(blank=True, null=True)
#     nombre = models.CharField(max_length=128, blank=True, null=True)
#     description = models.CharField(max_length=256, blank=True, null=True)

#     class Meta:
#         managed = False
#         db_table = 'Stadium'


# class Team(models.Model):
#     codigo = models.AutoField(primary_key=True)
#     equipo = models.CharField(max_length=128, blank=True, null=True)
#     liga = models.CharField(max_length=256, blank=True, null=True)

#     class Meta:
#         managed = False
#         db_table = 'Team'

from django.db import models


class City(models.Model):
    id = models.AutoField(primary_key=True)  #
    ciudad = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'City'


class Stadium(models.Model):
    num = models.AutoField(primary_key=True)
    estadio = models.IntegerField(blank=True, null=True)  # Agrega este campo
    nombre = models.CharField(max_length=128, blank=True, null=True)
    description = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Stadium'



class Team(models.Model):
    codigo = models.AutoField(primary_key=True)
    equipo = models.CharField(max_length=128, blank=True, null=True)
    liga = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Team'

class Relationship(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    stadium = models.ForeignKey(Stadium, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)


    def __str__(self):
        return f'Relationship {self.id}'
    

examen2/core/forms.py
from django import forms

from .models import *


class StadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        exclude = ["num"]
        widgets = {
            "estadio": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número del estadio"}),
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del estadio"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción del estadio"}),
        }

class UpdateStadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        exclude = ["num"]
        widgets = {
            "estadio": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número del estadio"}),
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del estadio"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción del estadio"}),
        }

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "equipo": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del equipo"}),
            "liga": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción de la liga"}),
        }

class UpdateTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "equipo": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del equipo"}),
            "liga": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción de la liga"}),
        }

class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        exclude = ["id"]
        widgets = {
            "ciudad": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre de la ciudad"}),
        }


class UpdateCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        exclude = ["id"]
        widgets = {
            "ciudad": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre de la ciudad"}),
        }

class RelationshipForm(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    stadium = models.ForeignKey(Stadium, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

examen2/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import *
from .models import *

# Create your views here.

##Estadio

class List1(generic.View):
    template_name = "core/list1.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Stadium.objects.all()
        self.context = {
            "stadiums": queryset  
        }
        return render(request, self.template_name, self.context)



class DetailStadium(generic.DetailView):
    template_name = "core/detail1.html"
    model = Stadium


class CreateStadium(generic.CreateView):
    template_name = "core/create1.html"
    model = Stadium
    form_class = StadiumForm
    success_url = reverse_lazy("core:list1")


class UpdateStadium(generic.UpdateView):
    template_name = "core/Update1.html"
    model = Stadium
    form_class = UpdateStadiumForm
    success_url = reverse_lazy("core:list1")

class DeleteStadium(generic.DeleteView):
    template_name = "core/delete1.html"
    model = Stadium
    success_url = reverse_lazy("core:list1")


##Equipos

class List2(generic.View):
    template_name = "core/list2.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Team.objects.all()
        self.context = {
            "Team": queryset
        }
        return render(request, self.template_name,self.context)
    
class CreateTeam(generic.CreateView):
    template_name = "core/create_team.html"
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy("core:list_teams")

    def form_valid(self, form):
        # Aquí puedes realizar operaciones adicionales si es necesario
        return super().form_valid(form)




class DetailTeam(generic.DetailView):
    template_name = "core/detail2.html"
    model = Team

class UpdateTeam(generic.UpdateView):
    template_name = "core/Update2.html"
    model = Team
    form_class = UpdateTeamForm
    success_url = reverse_lazy("core:list2")

class DeleteTeam(generic.DeleteView):
    template_name = "core/delete2.html"
    model = Team
    success_url = reverse_lazy("core:list2")

##Ciudades

class List3(generic.View):
    template_name = "core/list3.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = City.objects.all()
        self.context = {
            "City": queryset
        }
        return render(request, self.template_name,self.context)

class CreateCity(generic.CreateView):
    template_name = "core/create3.html"
    model = City
    form_class = CityForm
    success_url = reverse_lazy("core:list3")

class DetailCity(generic.DetailView):
    template_name = "core/detail3.html"
    model = City

class UpdateCity(generic.UpdateView):
    template_name = "core/Update3.html"
    model = City
    form_class = UpdateCityForm
    success_url = reverse_lazy("core:list3")

class DeleteCity(generic.DeleteView):
    template_name = "core/delete3.html"
    model = City
    success_url = reverse_lazy("core:list3")
    
    

def relationship_list(request):
    relationships = Relationship.objects.all()
    print(relationships)  # Imprime las relaciones en la consola del servidor
    return render(request, 'core/relationship_list.html', {'relationships': relationships})

examen2/templates/core/Update1.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Estadio
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar</button>
        <a href="{% url 'core:list1' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/Update2.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Equipos
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar</button>
        <a href="{% url 'core:list2' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/Update3.html
{% extends "base/base.html" %}

{% block title %}
  Actualziar Ciudades
{% endblock title %}

{% block content %}
<h1>Actualizar Ciudad</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-primary">Actualizar Ciudad</button>
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/create1.html
{% extends "base/base.html" %}

{% block title %}
  Crear estadio
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Anadir estadio</button>
        <a href="{% url 'core:list1' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/create2.html
{% extends "base/base.html" %}

{% block title %}
  Anadir Equipo
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Anadir Equipo</button>
        <a href="{% url 'core:list2' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/create3.html
{% extends "base/base.html" %}

{% block title %}
  Anadir City
{% endblock title %}

{% block content %}
<h1>Agregar Ciudad</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-success">Agregar Ciudad</button>
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/delete1.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Estadio
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Are you shure?: {{ object }}?
        <button type="submit" class="btn btn-outline-danger">Eliminar Estadio</button>
        <a href="{% url 'core:list1'%}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen2/templates/core/delete3.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Ciudad
{% endblock title %}

{% block content %}
<h1>Eliminar Ciudad</h1>
<p>¿Estás seguro de que quieres eliminar la ciudad "{{ City.ciudad }}"?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Sí, eliminar</button>
  <a href="{% url 'core:list3' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

examen2/templates/core/detail1.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL GRANTGOAL VIEW
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.gg_title }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the grantgoal: {{ object.gg_title }} .</strong> <br>
          Grantgoal Description: {{ object.description }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp {{ object.timestamp }} to grantgoal {{ object.gg_title }} </strong> with Duration {{ object.days_duration }} days, The Deadline grantgoal is: {{ object.final_date }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Grant Goal
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the status {{ object.status }} for the {{ object.gg_title }} </strong> Its state is: {{ object.state }}
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:list1' %}">back to list</a>
{% endblock content %}

examen2/templates/core/detail2.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL TEAM
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.gg_title }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the grantgoal: {{ object.gg_title }} .</strong> <br>
          Grantgoal Description: {{ object.description }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp {{ object.timestamp }} to grantgoal {{ object.gg_title }} </strong> with Duration {{ object.days_duration }} days, The Deadline grantgoal is: {{ object.final_date }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Grant Goal
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the status {{ object.status }} for the {{ object.gg_title }} </strong> Its state is: {{ object.state }}
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:list2' %}">back to list</a>
{% endblock content %}

examen2/templates/core/list1.html
{% extends 'base/base.html' %}

{% block title %} LIST STADIUMS {% endblock title %}

{% block content %}


    <a href="{% url 'core:create1' %}" class="btn btn-outline-success form-control">Add a New Stadium</a>
    <h1>Listado de Estadios</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Codigo de estadio</th>
            <th>Nombre de estadio</th>
            <th>Descripcion del estadio</th>
            <th></th>

        </thead>
        <tbody>
            {% for stadiums in stadiums %}  <!-- Cambiado de "Stadium" a "stadiums" -->
                <tr>
                    <td>{{ stadiums.num }}</td>
                    <td>{{ stadiums.nombre }}</td>
                    <td>{{ stadiums.description }}</td>
                    <td><a href="{% url 'core:detailone' stadiums.num %}" class="btn btn-outline-info">Detalles</a></td>
                    <td><a href="{% url 'core:Update1' stadiums.num %}" class="btn btn-outline-warning">Actualizar</a></td>
                    <td><a href="{% url 'core:delete1' stadiums.num %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
        
    </table>
   
{% endblock content %}

examen2/templates/core/list2.html
{% extends 'base/base.html' %}

{% block title %} Lista de equipos {% endblock title %}

{% block content %}


    <a href="{% url 'core:create2' %}" class="btn btn-outline-success form-control">Anadir nuevo equipo</a>
    <h1>Listado de Equipos</h1>
<table class="table">
  <thead>
    <tr>
      <th>Número</th>
      <th>Nombre del equipo</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for Teamm in Team %}
      <tr>
        <td>{{ Teamm.codigo }}</td>
        <td>{{ Teamm.equipo }}</td>
        <td>
          <a href="{% url 'core:detailtwo' Teamm.codigo %}" class="btn btn-outline-info">Detalles</a>
          <a href="{% url 'core:Update2' Teamm.codigo %}" class="btn btn-outline-warning">Actualizar</a>
          <a href="{% url 'core:delete2' Teamm.codigo %}" class="btn btn-outline-danger">Eliminar</a>
      </td>
      
      </tr>
    {% endfor %}
  </tbody>
</table>

    
{% endblock content %}

examen2/templates/core/list3.html
{% extends 'base/base.html' %}

{% block title %} Lista de ciudades {% endblock title %}

{% block content %}


    <a href="{% url 'core:create3' %}" class="btn btn-outline-success form-control">Anadir nueva ciudad</a>
    <h1>Listado de Ciudades</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Ciudad</th>
            <th></th>

        </thead>
        <tbody>
            {% for City in City %}
                <tr>
                    <td>{{ City.ciudad }}</td>
                    <td><a href="{% url 'core:detailthree' City.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:Update3' City.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{%  url 'core:delete3' City.id %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

examen2/templates/core/relationship_list.html
{% extends 'base/base.html' %}

{% block title %} Relaciones{% endblock title %}

{% block content %}

<h1> Relaciones </h1>
<table class="table">
   <thead>
      <tr>
         <th>Ciudad</th>
         <th>Estadio</th>
         <th>Equipo</th>
      </tr>
   </thead>
   <tbody>
      {% if relationships %}
         {% for relationship in relationships %}
            <tr>
               <td>{{ relationship.city }}</td>
               <td>{{ relationship.stadium }}</td>
               <td>{{ relationship.team }}</td>
            </tr>
         {% endfor %}
      {% else %}
         <tr>
            <td colspan="3">No hay relaciones disponibles.</td>
         </tr>
      {% endif %}
   </tbody>
</table>


 
 

{% endblock content %}